import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const evidence=JSON.parse(await readFile(new URL('../evidence/experiments.json',import.meta.url)));
const digest=createHash('sha256').update(await readFile(new URL('../engine.mjs',import.meta.url))).digest('hex');
if(digest!==evidence.sourceSha256)throw Error('Experiment source mismatch');
const assay=JSON.parse(await readFile(new URL('../evidence/connectome-assay.json',import.meta.url)));
const rows=evidence.rows;
const table=rows.map(r=>`| ${r.treatment} | ${r.seed} | ${r.population} | ${r.births} | ${r.deepestLineageEver} | ${r.meanNodes.toFixed(1)} | ${r.status} | ${r.achievedWorldSpeed.toFixed(1)}× |`).join('\n');
await writeFile(new URL('../evidence/validation.md',import.meta.url),`# Validation record\n\nEngine SHA-256: \`${digest}\`. Results match the packaged engine.\n\n${evidence.protocol}\n\n| Treatment | Seed | Final population | Births | Deepest ancestry | Mean living neurons | Outcome | Measured speed |\n|---|---:|---:|---:|---:|---:|---|---:|\n${table}\n\nMaximum absolute energy-accounting residual: ${Math.max(...rows.map(r=>Math.abs(r.accountingError)))} energy units.\n\nThe richer habitat sustained all tested populations, including frozen-learning controls. This does not establish a learning advantage. All low-resource populations became extinct without reseeding. These are artificial world seconds, not calibrated biological time. Default resource availability and founder food-seeking scaffolding were selected during development.\n\n## Full-connectome assay\n\nRetained neurons: ${assay.neurons}; directed edges: ${assay.edges}; synaptic contacts: ${assay.contacts}. Synthetic stimulus duration: ${assay.neural_ms} neural ms; measured wall time: ${assay.wall_seconds} seconds, excluding ${assay.load_seconds} seconds loading. Strict numeric checks: ${assay.strict_numeric_checks}. NumPy: ${assay.numpy_version}. Changed plastic edges: ${assay.changed_plastic_edges}. This demonstrates execution and weight changes, not functional learning or biological accuracy. The graph is not the controller of the reproducing ecosystem.\n\nThe initial system-Python/NumPy 2.0.2 assay emitted numerical warnings and failed when configured to raise on invalid numerical operations. A separate Python environment with NumPy ${assay.numpy_version} passed; the underlying cause was not established. Vendored neural code was not patched. See environment.json for versions.\n\n## Checks and limitations\n\nSee tests.txt for actual automated test output. JavaScript syntax and static DOM references were checked, and the local HTTP interface was exercised. Browser visual/interaction QA and supported-browser WebMCP verification were not performed. No claim of consciousness, civilization, unlimited brain growth, nested simulations or increased intelligence is supported.\n`);
